package mct.cli.cmd.kits

import arrow.core.raise.Raise
import com.github.ajalt.clikt.core.subcommands
import com.github.ajalt.clikt.parameters.options.default
import com.github.ajalt.clikt.parameters.options.option
import com.github.ajalt.clikt.parameters.options.required
import com.github.ajalt.clikt.parameters.types.choice
import mct.MCTError
import mct.cli.BaseCommand
import mct.cli.path
import mct.kit.TranslationMapping
import mct.kit.TranslationPool
import mct.mtl.MTLX
import mct.mtl.generateMTLXTemplate
import mct.mtl.translateByMTLX
import mct.util.io.readJson
import mct.util.io.readText
import mct.util.io.writeJson
import mct.util.io.writeText
import mct.util.unreachable

class MTLXKit : BaseCommand("mtlx", "MTLX Toolkit") {
    init {
        subcommands(Translate(), Generate())
    }

    private class Translate : BaseCommand("translate", help = "Use MTLX to translate text-pool") {
        val mtlxPath by option("--mtlx", "-m", help = "The path to mtlx file").path().required()
        val poolPath by option(
            "--pool",
            "-p",
            help = "The path to text pool generated by `text-pool` subcommand"
        ).path().required()
        val output by option("--output", "-o", help = "The output path to mapping file").path().required()

        context(_: Raise<MCTError>)
        override suspend fun App() {
            val mtlx = MTLX.fromString(mtlxPath.readText())
            val pool = poolPath.readJson<TranslationPool>()
            val mapping = pool.translateByMTLX(mtlx)
            val translatedCount = mapping.values.count { it != null }
            val untranslatedCount = mapping.values.size - translatedCount
            output.writeJson(mapping)
            logger.info { "Translate $translatedCount, missing $untranslatedCount" }
        }
    }


    private class Generate : BaseCommand("generate", help = "Generate a template MTLX file to help translate") {
        val poolPath by option(
            "--input",
            "-i",
            help = "The path to text pool generated by `text-pool` subcommand"
        ).path().required()
        val source by option("--source", "-s", help = "The source kind of the input").choice("pool", "mapping")
            .default("pool")
        val output by option("--output", "-o", help = "The output path to MTLX file").path().required()

        context(_: Raise<MCTError>)
        override suspend fun App() {
            val mtlx = when (source) {
                "pool" -> {
                    val pool = poolPath.readJson<TranslationPool>()
                    logger.info { "Pool has ${pool.size} entries" }
                    pool.generateMTLXTemplate()
                }

                "mapping" -> {
                    val mapping = poolPath.readJson<TranslationMapping>()
                    logger.info { "Mapping has ${mapping.size} entries" }
                    mapping.generateMTLXTemplate()
                }

                else -> unreachable
            }
            logger.info { "Generated MTLX (${mtlx.mtlMappings.size} mtls; ${mtlx.rawMappings.size} raws)" }
            output.writeText(mtlx.render())
            logger.info { "Written to $output" }
        }
    }
}